CREATE DATABASE IF NOT EXISTS otu CHARACTER SET utf8;

USE otu;

CREATE TABLE IF NOT EXISTS secrets (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  secret_type VARCHAR(255) NOT NULL,
  secret_uuid VARCHAR(1024) NOT NULL,
  secret_expire DATETIME,
  secret_expire BOOLEAN,
  created_at TIMESTAMP DEFAULT TO CURRENT_TIMESTAMP
);